# Generated by Django 3.0.6 on 2020-05-30 14:52

from django.db import migrations, models

import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200528_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=posts.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=posts.models.upload_location),
        ),
    ]
