# Generated by Django 3.0.6 on 2020-09-12 13:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default-profile.gif', upload_to=users.models.upload_location),
        ),
    ]
