# Generated by Django 3.0.4 on 2020-04-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200412_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
