# Generated by Django 2.2.4 on 2020-05-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200412_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='photo',
            new_name='image',
        ),
    ]
